### ISSUE TITLE
Deployment Environment

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-lsq921224#1]
#### As a developer I want a continuous deployment environment setup for my new Rails application.

Acceptance criteria:
- [x] [GitHub](https://github.com/AppFolioOnboarding) is used for source
  control.
- [x] The project's version of both Ruby and Rails are used both locally and on
  Heroku.
- [x] The landing page, `/`, provides some content.
- [x] Every available controller action has corresponding tests.
- [x] [CircleCI](https://circleci.com/) is used for Continuous Integration.
- [x] Heroku is used to deploy the application.
- [x] Pull requests are automatically deployed as review applications.
- [x] The staging application automatically deploys whenever the master branch
  is updated.
- [x] The staging application automatically deploys only after all tests pass
  on CircleCI.
- [x] The staging application deployment can be promoted to the production
  application deployment.
- [x] [Pronto](https://github.com/mmozuras/pronto) is used to help with code
  style consistency.

Discussion Topics:
- [ ] Where can we discover how long it takes to return an HTTP response?
- [ ] When should we commit our code?

References:
* https://rvm.io/rvm/install#try-out-your-new-rvm-installation
* http://guides.rubyonrails.org/getting_started.html
* http://guides.rubyonrails.org/testing.html#functional-tests-for-your-controllers
* https://devcenter.heroku.com/articles/getting-started-with-rails4
* https://devcenter.heroku.com/articles/pipelines
* https://github.com/bbatsov/ruby-style-guide

**Comment by bboe** [comment]
Can you update the label to "pull request" as there is now an open pull request?

**Comment by bboe** [comment]
I've reopened this issue so you can confirm that the staging deployment works properly. Assuming it does please promote it to production and then you can close the issue.

**Comment by lsq921224** [comment]
I reopened this issue because after the merge, db:setup appears so I have to remove it from app.json for now.
