### ISSUE TITLE
Modify Tag List

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-lsq921224#13]
#### As a user I want to edit the tag list for an image.

__Story__:

Image tags are awesome -- our user's love them! Tags help us make sense of the
plethora of images added to our system. But how annoying is it when our users
make spelling mistakes in their image tags? Super annoying! How awesome, and
useful would it be to allow for tags to be edited after an image is added?
Super awesome, and useful!

__Acceptance criteria__:
- [ ] There is a link to edit the tags for an image.
- [ ] The image whose tags are to be modified is displayed on the edit page.
- [ ] On the edit page, I can change the tags to any valid tag list.
- [ ] After saving the edit page with valid tags, my changes are visible
  throughout the rest of the application.

__Discussion__:
- [ ] Should an image's URL be editable?

__Dependencies__:
- Image Tags

**Comment by lsq921224** [comment]
@rmacklin @bboe I have a quick question, after the user successfully modify an image, should I redirect the user to the index page or the show page? I think show page makes more sense but it's causing me some trouble when writing flow test using page object per https://github.com/AppFolioOnboarding/image-sharer-lsq921224/issues/33#issuecomment-241870346.

**Comment by rmacklin** [comment]
> I think show page makes more sense

I agree.

> but it's causing me some trouble when writing flow test using page object per https://github.com/AppFolioOnboarding/image-sharer-lsq921224/issues/33#issuecomment-241870346.

I'll slack you to clarify what I meant by:

> To fix this, you'd need to use the block form of window.change_to in order to disambiguate the two pages.
