### ISSUE TITLE
Refactor flow tests to use page objects

### ISSUE THREAD

**Issue by rmacklin** [AppFolioOnboarding/image-sharer-lsq921224#33]
Reference material:
 - https://github.com/appfolio/ae_page_objects
 - https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project/flow-tests-with-page-objects

The starting skeleton is on the `flowTestsWithPageObjects` branch.

**Comment by lsq921224** [comment]
```
test 'add an image' do
    images_index_page = PageObjects::Images::IndexPage.visit

    new_image_page = images_index_page.add_new_image!
    puts new_image_page.instance_of? PageObjects::Images::NewPage
    tags = %w(foo bar)
    new_image_page = new_image_page.create_image!(link: 'invalid', tags: tags.join(', ')).as_a(PageObjects::Images::NewPage)
```
@rmacklin I am getting this error when running this test:
`Minitest::UnexpectedError: AePageObjects::CastError: Loaded page is not a PageObjects::Images::NewPage. Allowed pages: ["PageObjects::Images::IndexPage", "PageObjects::Images::NewPage"]`
And I don't know why.

This is my new_page object:
```
    class NewPage < PageObjects::Document
      path :new_image
      path :images

      form_for :image do
        element :link
        element :tag_list
      end

      def create_image!(link: nil, tags: nil)
        self.link.set link if link.present?
        self.tag_list.set tags if tags.present?
        node.click_button('Create Image')
        window.change_to(IndexPage, NewPage)
      end
    end
```

This is my create action in images_controller, which will render 'new' if image is invalid
```
  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to images_path, success: 'Image created successfully.'
    else
      render 'new', status: :unprocessable_entity
    end
  end
```

**Comment by rmacklin** [comment]
It looks like both the pages in your `window.change_to` call share a `path` declaration. AePageObjects cannot figure out which page should be loaded without more information, so it defaults to assuming it's the first page in the `window.change_to` list that matches the path. In this case, that's `IndexPage`, so the cast to `NewPage` fails.

To fix this, you'll need to use the block form of `window.change_to` in order to disambiguate the two pages. However, the fact that you're running into this is actually a result of making this undesired change: https://github.com/AppFolioOnboarding/image-sharer-lsq921224/pull/30#discussion_r75944267.

**Comment by lsq921224** [comment]
@rmacklin I run into another issue where I could not find a good way to implement `view!` in IndexPage
```
    class IndexPage < PageObjects::Document
      path :images

      collection :images, locator: '#images-list', item_locator: '.image-card-container', contains: ImageCard do
        def view!
          #
        end
      end
```
I have this problem because in the index page, I did not wrap my images with a link to the show page. I should have done that because otherwise my show page would be useless.
I opened a PR( #39 ) for this, and I hope you could take a look at it. thanks
