### ISSUE TITLE
Image Seeds

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-lsq921224#5]
#### As a developer I want at least 20 images to be created when I setup the database.

Acceptance criteria:
- [x] After running `rake db:setup` at least 20 images are shown in the
  homepage.
- [x] When a new app is deployed on heroku (e.g., every review app), that app
  automatically has at least 20 images on its homepage.

Dependencies:
- Image Index

**Comment by lsq921224** [comment]
closed by #23
